#MATPLOT LIB :- IS A PACKAGE USED  FOR PLOTTING THE GRAPH PROVIDED ARRAY
#MATPLOT IS USED ALONG WITH NUMPY PACKAGE AND NEVER ALONE
#MAT PLOT LIB HAS A FUNCTION PYPLOT
#PYPLOT IS FUNCTION USED FRO PLOTTING ON ARRRAY N FORM OF GRAPH
import matplotlib.pyplot as py
import numpy as np
x=np.array([2,6])
y=np.array([60,79])
py.plot(x,y)
py.show()
